// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/proto/configaudit.proto

package configauditpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigAudit_Scan_FullMethodName = "/configaudit.v1.ConfigAudit/Scan"
)

// ConfigAuditClient is the client API for ConfigAudit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigAuditClient interface {
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
}

type configAuditClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigAuditClient(cc grpc.ClientConnInterface) ConfigAuditClient {
	return &configAuditClient{cc}
}

func (c *configAuditClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, ConfigAudit_Scan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigAuditServer is the server API for ConfigAudit service.
// All implementations must embed UnimplementedConfigAuditServer
// for forward compatibility.
type ConfigAuditServer interface {
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
	mustEmbedUnimplementedConfigAuditServer()
}

// UnimplementedConfigAuditServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigAuditServer struct{}

func (UnimplementedConfigAuditServer) Scan(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedConfigAuditServer) mustEmbedUnimplementedConfigAuditServer() {}
func (UnimplementedConfigAuditServer) testEmbeddedByValue()                     {}

// UnsafeConfigAuditServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigAuditServer will
// result in compilation errors.
type UnsafeConfigAuditServer interface {
	mustEmbedUnimplementedConfigAuditServer()
}

func RegisterConfigAuditServer(s grpc.ServiceRegistrar, srv ConfigAuditServer) {
	// If the following call panics, it indicates UnimplementedConfigAuditServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigAudit_ServiceDesc, srv)
}

func _ConfigAudit_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigAuditServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigAudit_Scan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigAuditServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigAudit_ServiceDesc is the grpc.ServiceDesc for ConfigAudit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigAudit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configaudit.v1.ConfigAudit",
	HandlerType: (*ConfigAuditServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Scan",
			Handler:    _ConfigAudit_Scan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/configaudit.proto",
}
