// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/configaudit.proto

package configauditpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_api_proto_configaudit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_configaudit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_configaudit_proto_rawDescGZIP(), []int{0}
}

func (x *ScanRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ScanRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Problems      []*Problem             `protobuf:"bytes,1,rep,name=problems,proto3" json:"problems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_api_proto_configaudit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_configaudit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_configaudit_proto_rawDescGZIP(), []int{1}
}

func (x *ScanResponse) GetProblems() []*Problem {
	if x != nil {
		return x.Problems
	}
	return nil
}

type Problem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Severity       string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	Path           string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Recommendation string                 `protobuf:"bytes,4,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Problem) Reset() {
	*x = Problem{}
	mi := &file_api_proto_configaudit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Problem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Problem) ProtoMessage() {}

func (x *Problem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_configaudit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Problem.ProtoReflect.Descriptor instead.
func (*Problem) Descriptor() ([]byte, []int) {
	return file_api_proto_configaudit_proto_rawDescGZIP(), []int{2}
}

func (x *Problem) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Problem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Problem) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Problem) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

var File_api_proto_configaudit_proto protoreflect.FileDescriptor

const file_api_proto_configaudit_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/configaudit.proto\x12\x0econfigaudit.v1\"?\n" +
	"\vScanRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"C\n" +
	"\fScanResponse\x123\n" +
	"\bproblems\x18\x01 \x03(\v2\x17.configaudit.v1.ProblemR\bproblems\"{\n" +
	"\aProblem\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12&\n" +
	"\x0erecommendation\x18\x04 \x01(\tR\x0erecommendation2P\n" +
	"\vConfigAudit\x12A\n" +
	"\x04Scan\x12\x1b.configaudit.v1.ScanRequest\x1a\x1c.configaudit.v1.ScanResponseB%Z#configaudit/api/proto;configauditpbb\x06proto3"

var (
	file_api_proto_configaudit_proto_rawDescOnce sync.Once
	file_api_proto_configaudit_proto_rawDescData []byte
)

func file_api_proto_configaudit_proto_rawDescGZIP() []byte {
	file_api_proto_configaudit_proto_rawDescOnce.Do(func() {
		file_api_proto_configaudit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_configaudit_proto_rawDesc), len(file_api_proto_configaudit_proto_rawDesc)))
	})
	return file_api_proto_configaudit_proto_rawDescData
}

var file_api_proto_configaudit_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_configaudit_proto_goTypes = []any{
	(*ScanRequest)(nil),  // 0: configaudit.v1.ScanRequest
	(*ScanResponse)(nil), // 1: configaudit.v1.ScanResponse
	(*Problem)(nil),      // 2: configaudit.v1.Problem
}
var file_api_proto_configaudit_proto_depIdxs = []int32{
	2, // 0: configaudit.v1.ScanResponse.problems:type_name -> configaudit.v1.Problem
	0, // 1: configaudit.v1.ConfigAudit.Scan:input_type -> configaudit.v1.ScanRequest
	1, // 2: configaudit.v1.ConfigAudit.Scan:output_type -> configaudit.v1.ScanResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_configaudit_proto_init() }
func file_api_proto_configaudit_proto_init() {
	if File_api_proto_configaudit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_configaudit_proto_rawDesc), len(file_api_proto_configaudit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_configaudit_proto_goTypes,
		DependencyIndexes: file_api_proto_configaudit_proto_depIdxs,
		MessageInfos:      file_api_proto_configaudit_proto_msgTypes,
	}.Build()
	File_api_proto_configaudit_proto = out.File
	file_api_proto_configaudit_proto_goTypes = nil
	file_api_proto_configaudit_proto_depIdxs = nil
}
